logging:
  logs:
    default:
      level: INFO
storage:
  module: file_system
  root: /data
apps:
  tls:
    certificates:
      automate:
        - rtc.voople.app
        - turn.voople.app
        - rtc-ru.voople.ru
        - turn-ru.voople.ru
  layer4:
    servers:
      main:
        listen: [":443"]
        routes:
          - match:
              - tls:
                  sni:
                    - "turn.voople.app"
                    - "turn-ru.voople.ru"
            handle:
              - handler: tls
              - handler: proxy
                upstreams:
                  - dial: ["161.104.58.17:5349"]
          - match:
              - tls:
                  sni:
                    - "rtc.voople.app"
                    - "rtc-ru.voople.ru"
            handle:
              - handler: tls
                connection_policies:
                  - alpn: ["http/1.1"]
              - handler: proxy
                upstreams:
                  - dial: ["localhost:7880"]
